### ISSUE TITLE
Inclusion of LinuxSDK_v2020.11.0 is out

### ISSUE THREAD

**Issue by boom1** [levic/dektec#1]
Hello Levi,
I just wanted to ask if you could include the 2020.11.0 release of the LinuxSDK?
https://www.dektec.com/products/SDK/DTAPI/Downloads/LinuxSDK_v2020.11.0.tar.gz
Thank you!
Jens

**Comment by levic** [comment]
Sorry for not getting to this earlier; should be up to date as of last week

**Comment by boom1** [comment]
Thanks a lot!
